### ISSUE TITLE
bignum_divmod

### ISSUE THREAD

**Issue by monolifed** [kokke/tiny-bignum-c#1]
Since bignum_mod already does the division, it might be handy to have a function that gives both a/b and a%b in one call instead of calling both bignum_div and bignum_mod.

**Comment by kokke** [comment]
Hi @monolifed and thanks for your comment.

I agree. I'll add the divmod interface to the header file and let the div and mod functions wrap divmod. 

Are you looking to use the code for RSA?

**Comment by monolifed** [comment]
Nice. I am looking to use it for some type of PRNG for creating [passwords](https://github.com/monolifed/lesspassc/blob/master/lp.c#L84).
```
random = entropy % range; entropy = entropy/range
```
I am currently using openssl but I want to replace it.

**Comment by kokke** [comment]
@dudedsy fixed this outstanding issue: https://github.com/kokke/tiny-bignum-c/pull/4
