### ISSUE TITLE
RSA does not work

### ISSUE THREAD

**Issue by qdk0901** [kokke/tiny-bignum-c#13]
Hi,
   When I run the RSA test case, it output empty decrypt result.

**Comment by kokke** [comment]
Hi @qdk0901 and thanks for your interest in the project :)

The RSA-code works fine, but expects at least 2048bit bignums, and the default size is 1024. 
For this reason among others, I have commented-out the RSA-test in the Makefile (as you may have noticed).

I also did not want people to start writing cryptography code with this library. For crypto code, you want constant-time operations, which this module does not implement. That makes the code vulnerable to timing attacks, if used to implement crypto primitives, so beware :)
Vanilla RSA also has many traps/foot-guns, so you should not use this for serious business.

However, to answer your question:
**You can change the default key-size from 1024 bits (128 bytes) to 2048 bits (256 bytes), by changing ** `#define BN_ARRAY_SIZE    (128 / WORD_SIZE)` **=>** `#define BN_ARRAY_SIZE    (256 / WORD_SIZE)` **in `bn.h` and that should make the RSA code work again.**

Let me know if that works for you :)

**Comment by qdk0901** [comment]
Sorry for late reply. Yes, it works when I change key-size from 128 bytes to 256 bytes. This test case is great!

**Comment by kokke** [comment]
Hi @qdk0901 - no worries :) 

I hope you got everything working as expected.
