### ISSUE TITLE
What is the maximum size of a tiny-bignum-c bignum in bits?

### ISSUE THREAD

**Issue by dave-goodall** [kokke/tiny-bignum-c#20]
1. Can you please clarify the maximum size of a bignum in bits?

 bn.h states that 

 a A 1024 bit integer takes up 128 bytes RAM, implying that the library supports at least that.

 b.But for a WORD_SIZE of 4 (which appears to the the maximum) bn.h also states that 
   the size of big numbers in bytes BN_ARRAY_SIZE is 128/WORD_SIZE which = 32 bytes or 32 *8 bits/byte = 256 bits 

 c.The data holding structure (Array of DTYPES) is DTYPE array[BN_ARRAY_SIZE]
   For WORD_SIZE == 4 DTYPE is a uint32_t (32 bits) and * (per b.) BN_ARRAY_SIZE = 256 bits
   which gives 32 * 256 = 8192 bits   
 
 I attach below the output from a test tool (kblt) and the 'c' source for it.
 
 Using the  bignum_pow function 
 2^607  appears to be evaluated correctly but
 2^1279 which is comfortably over 1024 bits is evaluated to 0
 which inclines me to the conclusion that tiny-bignum-c supports up to 1024 bit integers.

 2. A second question which I am uncertain about, is whether DTYPE_TMP, 
    which for WORD_SIZE == 4 is a uint64_t 64-bit value
    may in fact constrain results to only 64-bits 
    
    in the functions where it is used directly.
    bignum_from_int()
    bignum_inc()
    bignum_add()
    bignum_sub()
    bignum_mul()
    bignum_div()
    
    and functions that depend on the above
    bignum_divmod()
    bignum_pow()
    bignum_isqrt()

    I have seen no evidence of this in bignum code I have written using bignum_from_int(),
    divmod, pow, and isqrtbut i would appreciate clarification on this.

  I appreciate the clarity and cleanness of the code and thank you for it.

  dave 
    
 

==== kblt output =========================================================================================

kblt Version 1.0 Build 02 (c) ZDS LLC 2020 started

 bignum WORD_SIZE = 4
 bignum BN_ARRAY_SIZE (size of big-numbers) :  32 (bytes)  256 (bits)
 bignum MAX_VAL (of DTYPE_TMP) :  4294967295 (bits)  4,294,967,296 -1  16^8 or 2^32 (bits)

 2^7 Result Hex =     80
       Expected Hex=[0x80]
       Expected Dec=[128]

 2^19 Result Hex =     80000
       Expected Hex=[0x80000]
       Expected Dec=[524288]

 2^31 Result Hex =     80000000
       Expected Hex=[0x80000000]
       Expected Dec=[2147483648]

 2^61 Result Hex =     2000000000000000
       Expected Hex=[0x2000000000000000]
       Expected Dec=[2305843009213693952]

 2^63 Result Hex =     8000000000000000
       Expected Hex=[0x8000000000000000]
       Expected Dec=[9223372036854775808]

 2^64 Result Hex =     10000000000000000
       Expected Hex=[0x10000000000000000]
       Expected Dec=[18446744073709551616]

 2^65 Result Hex =     20000000000000000
       Expected Hex=[0x20000000000000000]
       Expected Dec=[36893488147419103232]

 2^89 Result Hex =     20000000000000000000000
       Expected Hex=[0x20000000000000000000000]
       Expected Dec=[618970019642690137449562112]

 2^127 Result Hex =     80000000000000000000000000000000
       Expected Hex=[0x80000000000000000000000000000000]
       Expected Dec=[170141183460469231731687303715884105728]

 2^521 Result Hex =     20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
       Expected Hex=[0x20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
       Expected Dec=[6864797660130609714981900799081393217269435300143305409394463459185543183397656052122559640661454554977296311391480858037121987999716643812574028291115057152]

 2^607 Result Hex =     80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
       Expected Hex=[0x80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
       Expected Dec=[531137992816767098689588206552468627329593117727031923199444138200403559860852242739162502265229285668889329486246501015346579337652707239409519978766587351943831270835393219031728128]

 2^1279 Result Hex =
       Expected Hex=[0x80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
       Expected Dec=[10407932194664399081925240327364085538615262247266704805319112350403608059673360298012239441732324184842421613954281007791383566248323464908139906605677320762924129509389220345773183349661583550472959420547689811211693677147548478866962501384438260291732348885311160828538416585028255604666224831890918801847068222203140521026698435488732958028878050869736186900714720710555703168729088]

 kblt Version 1.0 Build 02 (c) ZDS LLC 2020 completed

==== kblt.c source =======================================================================================

//
// Program   : kblt : kokke_bignum_limit_test
// Author    : Dave Goodall, ZDS LLC dave.goodall@gmail.com
// Syntax    : kblt
// Function  : Test 2^n limit of bignum package

// Suppress Microsoft Visual Studio 2019 pestilential ERRORS
// "C4996: 'ctime': This function or variable may be unsafe. Consider using ctime_s instead."
#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <time.h>            // time_t
#include <stdlib.h>          // malloc free
#include "bn.h"
#include <inttypes.h>        // sprintf specifier uint64_t
#include <string.h>

// ----------------------------------------------------------------------

#define PROGRAM_NAME "kblt"

#define VERSION "1.0 Build 02"      // 10/20/2090
//                                  1. Add powTest()
//                                  2. Extend tests past the 1024 bit limit(?)
//              "1.0 Build 01"      // 10/19/2090
//                                  1. First clean compile
//                                     Discrete test c cases

typedef enum
{
    false = 0,
    true  = 1,
} bool;

// Files ------------------------------------------------------------------
#define STRING_SIZE_DEC      262144  // Hex 0x40000
#define STRING_SIZE_HEX      0x40000
char szString[STRING_SIZE_HEX];

// ------------------------------------------------------------------------
// Log File

#define MSG_LEN            524288  // Hex 0x80000
#define LOG_FILE_EXT       "log"

FILE *fdLogFile;                   // File descriptor
char szLogFileName[128];
char  szLogFileBuf[MSG_LEN];       // File buffer
bool  bLogFile;                    // File available

// ------------------------------------------------------------------------

DTYPE_TMP  dt_base = 2;

DTYPE_TMP  dt_exponent_31 = 31;
DTYPE_TMP  dt_exponent_61 = 61;
DTYPE_TMP  dt_exponent_63 = 63;
DTYPE_TMP  dt_exponent_64 = 64;
DTYPE_TMP  dt_exponent_65 = 65;
DTYPE_TMP  dt_exponent_89 = 89;
DTYPE_TMP  dt_exponent_127 = 127;
DTYPE_TMP  dt_exponent_521 = 521;

// Global to simplify parameter passing
struct bn bn_base;
struct bn bn_exponent;
struct bn bn_result;

// ------------------------------------------------------------------------
// Prototypes
void powTest(DTYPE_TMP dt_exponent, char* cpExpectedHex, char* cpExpectedDec);
extern void logPrint( char * cpBuf, bool bCloseFile);
void syntax();

int main(int argc, char** argv) {

   //------------------------------------------------------------------------
    // Open the log file for appending
    sprintf(szLogFileName, "%s.%s", PROGRAM_NAME, LOG_FILE_EXT);
    fdLogFile = fopen(szLogFileName, "a+");
    if (fdLogFile != NULL) {
        bLogFile = true;
    }

    //------------------------------------------------------------------------
    // Now logging can start...
    sprintf(szLogFileBuf, "%s Version %s (c) ZDS LLC 2020 started\n", PROGRAM_NAME, VERSION);
    logPrint(szLogFileBuf, false);

    // Display bignum configuration parameters
    sprintf(szLogFileBuf, "bignum WORD_SIZE = %d", WORD_SIZE);
    logPrint(szLogFileBuf, false);

    sprintf(szLogFileBuf, "bignum BN_ARRAY_SIZE (size of big-numbers) :  %d (bytes)  %d (bits)", BN_ARRAY_SIZE, BN_ARRAY_SIZE*8);
    logPrint(szLogFileBuf, false);

    sprintf(szLogFileBuf, "bignum MAX_VAL (of DTYPE_TMP) :  %I64u (bits)  %s (bits)\n\n", MAX_VAL, "4,294,967,296 -1  16^8 or 2^32");
    logPrint(szLogFileBuf, false);

    bignum_from_int(&bn_base, dt_base);  // ( bignum_int does an internal bignum_init(n) )

    // Power computations:                 https://www.mathsisfun.com/calculator-precision.html
    //                                     http://lcn2.github.io/mersenne-english-name/m1279/prime-c-e.html
    // Decimal to Hexadecimal converter:   https://www.rapidtables.com/convert/number/decimal-to-hex.html 

    // Evaluate  2^n     {Expected Hex}  {Expected Dec}
    // Note: String size STRING_SIZE_HEX must be manually adjusted to exceed the maximum needed by the largest power
    // For example : // 31-11 61-19 63-19 64-20 65-20 89-26 127-35 521-134 607-184 1279-385
    
    powTest((DTYPE_TMP)7, "0x80", "128");
    powTest((DTYPE_TMP)19, "0x80000", "524288");
    powTest((DTYPE_TMP)31, "0x80000000",          "2147483648" );
    powTest((DTYPE_TMP)61, "0x2000000000000000",  "2305843009213693952");
    powTest((DTYPE_TMP)63, "0x8000000000000000",  "9223372036854775808");
    powTest((DTYPE_TMP)64, "0x10000000000000000", "18446744073709551616");
    powTest((DTYPE_TMP)65, "0x20000000000000000", "36893488147419103232");
    powTest((DTYPE_TMP)89, "0x20000000000000000000000", "618970019642690137449562112");
    powTest((DTYPE_TMP)127, "0x80000000000000000000000000000000", "170141183460469231731687303715884105728");
    powTest((DTYPE_TMP)521, "0x20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", 
    "6864797660130609714981900799081393217269435300143305409394463459185543183397656052122559640661454554977296311391480858037121987999716643812574028291115057152");

    powTest((DTYPE_TMP)607, "0x80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","531137992816767098689588206552468627329593117727031923199444138200403559860852242739162502265229285668889329486246501015346579337652707239409519978766587351943831270835393219031728128");
  
    // 1279 (Past the 1024 bit integer specified in bn.h)
    // 10407932194664399081925240327364085538615262247266704805319112350403608059673360298012239441732324184842421613954281007791383566248323464908139906605677320762924129509389220345773183349661583550472959420547689811211693677147548478866962501384438260291732348885311160828538416585028255604666224831890918801847068222203140521026698435488732958028878050869736186900714720710555703168729088
    powTest((DTYPE_TMP)1279, "0x80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "10407932194664399081925240327364085538615262247266704805319112350403608059673360298012239441732324184842421613954281007791383566248323464908139906605677320762924129509389220345773183349661583550472959420547689811211693677147548478866962501384438260291732348885311160828538416585028255604666224831890918801847068222203140521026698435488732958028878050869736186900714720710555703168729088");

    sprintf(szLogFileBuf,"%s Version %s (c) ZDS LLC 2020 completed\n\n", PROGRAM_NAME, VERSION );
    logPrint(szLogFileBuf, true);

    // Cleanup
   if (bLogFile)
       fclose (fdLogFile);

    return 0;
}

void powTest(DTYPE_TMP dt_exponent, char* cpExpectedHex, char* cpExpectedDec) {

    bignum_from_int(&bn_exponent, dt_exponent);  // ( bignum_int does an internal bignum_init(n) )
    bignum_pow(&bn_base, &bn_exponent, &bn_result); // ( bignum_pow does an internal bignum_init(c) )
    memset(szString, '\0', sizeof(szString));
    bignum_to_string(&bn_result, szString, sizeof(szString));
    printf(" 2^%I64u Result Hex =     %-170.170s\n       Expected Hex=[%s]\n       Expected Dec=[%s]\n\n", dt_exponent, szString, cpExpectedHex, cpExpectedDec);
}

// Log and Display message
void logPrint( char * cpBuf, bool bCloseFile) {

    if (bLogFile) {
       fprintf(fdLogFile, " %s\n", cpBuf);
       fflush(fdLogFile);
       if (bCloseFile) {
           fclose(fdLogFile);
        }
    }
    printf("\n %s", cpBuf);
}

//---------------------------------------------------------------------------
//  Required   [r]
//  {Optional} {o}

void syntax() {
   printf("\n\n Syntax: [required] {optional}\n\n");
   printf(" %s \n", PROGRAM_NAME);
}

// --- End Program --------------------------------------------------------

**Comment by kokke** [comment]
Hi @dave-goodall and thanks for your kind words :)

Per default the integers are 1024 bits wide (128 bytes).
You can define the size in `bn.h` 

```C
/* Size of big-numbers in bytes */
#define BN_ARRAY_SIZE    (128 / WORD_SIZE)
```

So if you want, say 2048 bits integers (256 bytes) you replace the 128 with 256.

BN_ARRAY_SIZE determines the size of an array of integers of WORD_SIZE bytes, hence the division.

I agree with you that it is not very clear how to change the size of the bignumbers, without knowing beforehand.


```A second question which I am uncertain about, is whether DTYPE_TMP,
which for WORD_SIZE == 4 is a uint64_t 64-bit value
may in fact constrain results to only 64-bits
```

DTYPE_TMP is only used for calculations word-by-word, so yes for WORD_SIZE == 4 the temporary results of operands on two 32-bit integers are limited to 64 bit - which should be exactly sufficient.





Hope I answered your question :)
