### ISSUE TITLE
Bug in bignum_add

### ISSUE THREAD

**Issue by XYlearn** [kokke/tiny-bignum-c#3]
in function bignum_add at line 215
```C
DTYPE_TMP tmp;
int carry = 0;
for (i = 0; i < BN_ARRAY_SIZE; ++i)
{
  tmp = a->array[i] + b->array[i] + carry;
  carry = (tmp > MAX_VAL);  // will always be false
  c->array[i] = (tmp & MAX_VAL);
}
```
`tmp > MAX_VAL` will always be false because the result of `a->array[i] + b->array[i] + carry` will always be truncated to DTYPE. 
To verify that you can try bignum_add between -1 and 3
To fix it, convert the type of a->array[i] to DTYPE_TMP.

**Comment by kokke** [comment]
Hi @XYlearn and thank you for taking an interest in this project :)

I am not sure I understand your example. You mention -1 and 3, but -1 is a signed value and the project only supports unsigned integers (and does not correctly handle overflow by the way).

Can you provide me with a test-case that demonstrates the bug, like `test_evil()` in [tests/hand_picked.c](https://github.com/kokke/tiny-bignum-c/blob/master/tests/hand_picked.c) or the test-cases in [tests/golden.c](https://github.com/kokke/tiny-bignum-c/blob/master/tests/golden.c) or something similar?

**Comment by XYlearn** [comment]
I write test_case as below
```C
#include "bn.h"
#include <stdio.h>

int main() {
	struct bn n1;
	struct bn n2;
	char buf[0x200];

	bignum_from_int(&n1, 0);
	bignum_from_int(&n2, 1);
	bignum_sub(&n1, &n2, &n1);
	bignum_from_int(&n2, 3);
	bignum_add(&n1, &n2, &n1);
	bignum_to_string(&n1, buf, sizeof(buf));

	printf("0 - 1 + 3 = %s\n", buf);

	return 0;
}
```
The result is `0 - 1 + 3 = ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000002`
But 2 is expected.

**Comment by kokke** [comment]
Hi @XYlearn and thanks for the example test case :)

I have pushed a few changes that fixes the bug and adds your test-case to the test-suite.

Thanks for your contribution
